spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/testdb
    username: sa
    password: null
  jpa:
    hibernate:
      ddl-auto: update